//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estate()
        {
            this.Offers = new HashSet<Offer>();
        }
    
        public int Id { get; set; }
        public string CityAddress { get; set; }
        public string StreetAddress { get; set; }
        public string HouseNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public Nullable<int> NumberOfStroyes { get; set; }
        public Nullable<int> NumberOfRooms { get; set; }
        public Nullable<double> TotalArea { get; set; }
        public int IdTypeOfEstate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        public virtual TypesOfEstate TypesOfEstate { get; set; }
    }
}
