//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esoftDBEntities : DbContext
    {
        public esoftDBEntities()
            : base("name=esoftDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Demand> Demands { get; set; }
        public virtual DbSet<Estate> Estates { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<Realtor> Realtors { get; set; }
        public virtual DbSet<TypesOfEstate> TypesOfEstates { get; set; }
    }
}
