//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdRealtor { get; set; }
        public int IdEstate { get; set; }
        public int Price { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Estate Estate { get; set; }
        public virtual Realtor Realtor { get; set; }
    }
}
